stages:
  restructure:
    # cmd: python3 src/restructure.py assets/data/raw/20200511-1159.csv 
    cmd: python3 src/restructure.py assets/data/raw/*.csv
    deps:
    - assets/data/raw
    - src/restructure.py
    outs:
    - assets/data/restructured
  featurize:
    cmd: python3 src/featurize.py assets/data/restructured/*.csv
    deps:
    - assets/data/restructured
    - src/featurize.py
    outs:
    - assets/data/featurized
  sequentialize:
    cmd: python3 src/sequentialize.py assets/data/featurized/*.csv
    deps:
    - assets/data/featurized
    - src/sequentialize.py
    outs:
    - assets/data/sequentialized
  split:
    cmd: python3 src/split.py assets/data/sequentialized/*.npz
    deps:
    - assets/data/sequentialized
    - src/split.py
    outs:
    - assets/data/split
  scale:
    cmd: python3 src/scale.py assets/data/split/train.npz assets/data/split/test.npz
    deps:
    - assets/data/split
    - src/scale.py
    outs:
    - assets/data/scaled
  train:
    cmd: python3 src/train.py assets/data/scaled/train.npz
    deps:
    - assets/data/scaled
    - src/train.py
    - src/model.py
    outs:
    - assets/models
  evaluate:
    cmd: python src/evaluate.py assets/models/model.h5 assets/data/scaled/test.npz
    deps:
    - assets/data/scaled/test.npz
    - assets/models/model.h5
    - src/evaluate.py
    metrics:
    - assets/metrics/metrics.json:
        cache: false
