stages:

  restructure:
    cmd: python3 src/restructure.py assets/data/raw/*.csv
    deps:
    - assets/data/raw
    - src/restructure.py
    outs:
    - assets/data/restructured

  featurize:
    cmd: python3 src/featurize.py assets/data/restructured/*.csv
    deps:
    - assets/data/restructured
    - src/featurize.py
    outs:
    - assets/data/featurized
    params:
    - featurize.delete
    - featurize.features
    - featurize.remove
    - featurize.scale

  sequentialize:
    cmd: python3 src/sequentialize.py assets/data/featurized/*.csv
    deps:
    - assets/data/featurized
    - src/sequentialize.py
    outs:
    - assets/data/sequentialized
    params:
    - sequentialize.hist_size

  split:
    cmd: python3 src/split.py assets/data/sequentialized/*.npz
    deps:
    - assets/data/sequentialized
    - src/split.py
    outs:
    - assets/data/split
    params:
    - split.train_split

  scale:
    cmd: python3 src/scale.py assets/data/split/train.npz assets/data/split/test.npz
    deps:
    - assets/data/split
    - src/scale.py
    outs:
    - assets/data/scaled
    params:
    - scale.method
    - scale.breathing_min
    - scale.breathing_max
    - scale.heartrate_min
    - scale.heartrate_max

  train:
    cmd: python3 src/train.py assets/data/scaled/train.npz
    deps:
    - assets/data/scaled
    - src/train.py
    - src/model.py
    outs:
    - assets/models
    params:
    - train.net
    - train.n_epochs
    - train.batch_size

  evaluate:
    cmd: python src/evaluate.py assets/models/model.h5 assets/data/scaled/test.npz
    deps:
    - assets/data/scaled/test.npz
    - assets/models/model.h5
    - src/evaluate.py
    metrics:
    - assets/metrics/metrics.json:
        cache: false
