stages:
  restructure:
    cmd: python3 src/restructure.py assets/data/raw/20200511-1159.csv assets/data/raw/20200512-1108.csv
      assets/data/raw/20200513-1053.csv assets/data/raw/20200622-2106.csv assets/data/raw/20200727-2055.csv
      assets/data/raw/20200811-1726.csv assets/data/raw/20200812-1943.csv assets/data/raw/20200813-2012.csv
    deps:
    - assets/data/raw
    - src/restructure.py
    outs:
    - assets/data/restructured
  featurize:
    cmd: python3 src/featurize.py assets/data/restructured/20200511-1159-restructured.csv
      assets/data/restructured/20200512-1108-restructured.csv assets/data/restructured/20200513-1053-restructured.csv
      assets/data/restructured/20200622-2106-restructured.csv assets/data/restructured/20200727-2055-restructured.csv
      assets/data/restructured/20200811-1726-restructured.csv assets/data/restructured/20200812-1943-restructured.csv
      assets/data/restructured/20200813-2012-restructured.csv
    deps:
    - assets/data/restructured
    - src/featurize.py
    outs:
    - assets/data/featurized
  sequentialize:
    cmd: python3 src/sequentialize.py assets/data/featurized/20200511-1159-featurized.csv
      assets/data/featurized/20200512-1108-featurized.csv assets/data/featurized/20200513-1053-featurized.csv
      assets/data/featurized/20200622-2106-featurized.csv assets/data/featurized/20200727-2055-featurized.csv
      assets/data/featurized/20200811-1726-featurized.csv assets/data/featurized/20200812-1943-featurized.csv
      assets/data/featurized/20200813-2012-featurized.csv
    deps:
    - assets/data/featurized
    - src/sequentialize.py
    outs:
    - assets/data/sequentialized
  split:
    cmd: python3 src/split.py assets/data/sequentialized/20200511-1159-sequentialized.npz
      assets/data/sequentialized/20200512-1108-sequentialized.npz assets/data/sequentialized/20200513-1053-sequentialized.npz
      assets/data/sequentialized/20200622-2106-sequentialized.npz assets/data/sequentialized/20200727-2055-sequentialized.npz
      assets/data/sequentialized/20200811-1726-sequentialized.npz assets/data/sequentialized/20200812-1943-sequentialized.npz
      assets/data/sequentialized/20200813-2012-sequentialized.npz
    deps:
    - assets/data/sequentialized
    - src/split.py
    outs:
    - assets/data/split
  scale:
    cmd: python3 src/scale.py assets/data/split/train.npz assets/data/split/test.npz
    deps:
    - assets/data/split
    - src/scale.py
    outs:
    - assets/data/scaled
