restructure:

featurize:
  # The variables listed under 'delete' is deleted before starting preprocessing,
  # and should only be done to variables that are not going to be used at all.
  delete:
    - time
    - calories
  features:
    # - ribcage_min
    # - ribcage_max
    #- r ibcage_range
      #- abdomen_range 
      #- ribcage_gradient
      #- abdomen_gradient
    # - heartrate_gradient
    #- ribcage_frequency
    #- abdomen_frequency
    # - ribcage_slope
    # - abdomen_slope
    - ribcage_slope_cyclic
    - abdomen_slope_cyclic
      #- heartrate_slope_cyclic
  # The variables listed under 'remove' is removed after adding additional
  # features, which means that they might be used for feature engineering, but
  # should not be used as input the the neural network.
  remove:
          - ribcage
          - abdomen
          - heartrate
  breathing_min: 0
  breathing_max: 4096
  heartrate_min: 35
  heartrate_max: 185
  scale: True
  range_window: 50
  range_smoothing: 50
  slope_shift: 1
  slope_smoothing: 100
  slope_abs: True
  # If 'diff_targets' > 0, the change in the target value will be used as
  # target, and the value 'diff_targets' will indicate the step size when
  # calculating the change/difference.
  diff_targets: 0

split:
  train_split: 0.7

scale:
  method: none
  output: minmax

sequentialize:
  # History window size in deciseconds
  hist_size: 100
  # Use only every nth element
  use_elements: 1
  # Use mean power value over given window
  target_mean_window: 1

train:
  net: cnn
  n_epochs: 400
  batch_size: 128
  kernel_size: 6
  weigh_samples: False
  weight_thresh: 250
  weight: 1.5
  autoencode: False
  early_stopping: True

evaluate:
  smooth_targets: 0
  save_y: True
