restructure:

featurize:
  delete:
    - time
    - calories
  features:
    # - ribcage_min
    # - ribcage_max
    - ribcage_range
    - abdomen_range
  remove:
    # - ribcage
    # - abdomen
    # - heartrate
  scale: True

sequentialize:
  # History window size in deciseconds
  hist_size: 10
  # Use only every nth element
  use_elements: 1

combine:

split:
  train_split: 0.8

scale:
  method: minmax
  breathing_min: 0
  breathing_max: 4096
  heartrate_min: 35
  heartrate_max: 185

train:
  net: cnn
  n_epochs: 5
  batch_size: 128

evaluate:
