restructure:

featurize:
  delete:
    - time
    - calories
  features:
    # - ribcage_min
    # - ribcage_max
    # - ribcage_range
    # - abdomen_range
    # - ribcage_gradient
    # - abdomen_gradient
    # - ribcage_frequency
    # - abdomen_frequency
    # - ribcage_slope
    # - abdomen_slope
    # - ribcage_slope_cyclic
    # - abdomen_slope_cyclic
  remove:
    # - ribcage
    # - abdomen
    # - heartrate
  breathing_min: 0
  breathing_max: 4096
  heartrate_min: 35
  heartrate_max: 185
  scale: True
  range_window: 50
  slope_shift: 2
  slope_smoothing: 100
  slope_abs: False

split:
  train_split: 0.6

scale:
  method: minmax

sequentialize:
  # History window size in deciseconds
  hist_size: 100
  # Use only every nth element
  use_elements: 1
  # Use mean power value over given window
  target_mean_window: 1

train:
  net: cnn
  n_epochs: 1
  batch_size: 128
  kernel_size: 4

evaluate:
