restructure:

featurize:
  remove:
    - time
    - calories
    - abdomen
  features:

sequentialize:
  hist_size: 100 # milliseconds

combine:

split:
  train_split: 0.7

scale:
  method: minmax

train:
  net: cnn
  n_epochs: 10
  batch_size: 128

evaluate:

