restructure:

featurize:
  delete:
    - time
    - calories
    - abdomen
  features:
    - ribcage_min
    - ribcage_max
    - ribcage_range
  remove:
    - ribcage

sequentialize:
  hist_size: 200 # milliseconds

combine:

split:
  train_split: 0.8

scale:
  method: minmax
  heartrate_min: 35
  heartrate_max: 185

train:
  net: cnn
  n_epochs: 1
  batch_size: 128

evaluate:
