restructure:

featurize:
  delete:
    - time
    - calories
  features:
    # - ribcage_min
    # - ribcage_max
    - ribcage_range
    - abdomen_range
  remove:
    # - ribcage
    # - abdomen
    # - heartrate
  scale: True

sequentialize:
  hist_size:    100 # milliseconds
  use_elements:  10 # use only every n-th sequence

combine:

split:
  train_split: 0.8

scale:
  method: minmax
  breathing_min: 0
  breathing_max: 4096
  heartrate_min: 35
  heartrate_max: 185

train:
  net: cnn
  n_epochs: 1
  batch_size: 128

evaluate:
