#!/bin/bash

# python src/restructure.py assets/data/raw/*
python src/featurize.py assets/data/restructured/*
python src/sequentialize.py assets/data/featurized/*
python src/split.py assets/data/sequentialized/*
python src/train.py assets/data/split/train.npz
